### ISSUE TITLE
[ppa] current stable version has  https://github.com/ansible/ansible/issues/10550 bug

### ISSUE THREAD

**Issue by erickeller** [ansible/ansible-docker-base#10]
The current docker base stable version is not useful since Bug: https://github.com/ansible/ansible/issues/10550 prevent using sudo at some place.

the ppa stable debian package needs to be published.

**Comment by bcoca** [comment]
I'm not sure what this ticket is for, the bug was fixed and will be published with next release.

**Comment by erickeller** [comment]
FROM ansible/ubuntu14.04-ansible:stable
...
RUN ansible-playbook test.yml -c local
...


I get the following error:

```
TASK: [test | copy the test.conf to home] ************************* 
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 590, in _executor
    msg = str(ae)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 792, in _executor_internal
    raise errors.AnsibleError("lookup plugins (with_*) cannot be used with async tasks")
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1027, in _executor_internal_inner
  File "/usr/lib/pymodules/python2.7/ansible/runner/action_plugins/copy.py", line 237, in run
    if self.runner.become and self.runner.become_user != 'root' and not raw:
AttributeError: 'Runner' object has no attribute 'become'
```

if I use the ubuntu14.04-ansible:devel everything works fine

**Comment by bcoca** [comment]
Yes, that is another bug that was fixed and will be released in the next stable, I'm still not clear what you opened this ticket for.

**Comment by erickeller** [comment]
The current docker stable image is unusable that's why I filled out a bug
report. But you can close since the workaround is to use the devel image.

Best regards

**Comment by bcoca** [comment]
ah, you wanted to post an issue here https://github.com/ansible/ansible-docker-base
