### ISSUE TITLE
Docker API Error: client is too old, minimum supported API version is 1.12

### ISSUE THREAD

**Issue by mysterytree** [ansible/ansible-docker-base#18]
When I deploy a container by using ansible. I get an error puzzled me a lot:

Docker API Error: client is too old, minimum supported API version is 1.12

please upgrade your client to a newer version

My docker :+1: 

Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:37:18 UTC 2015
 OS/Arch:      linux/amd64

docker-py

Name: docker-py
Version: 1.5.0

I have try docker-py 1.1.0/1.2.3/1.5.0 and get same error

what can i do?

**Comment by mattclay** [comment]
These images have been [deprecated](https://github.com/ansible/ansible-docker-base/blob/master/README.md#these-images-have-been-deprecated) and are no longer supported.
