### ISSUE TITLE
Specific version of docker-py is required for ansible-docker on centos 7

### ISSUE THREAD

**Issue by amyfang** [ansible/ansible-docker-base#19]
When using ansible with docker module on centos 7, it requires specific docker-py v1.2.3. Other versions don't work. The error message is: 

TASK: [test_redis] ************************************************************

failed: [localhost] => {"changed": false, "failed": true}

msg: Docker API Error: client is newer than server (client API version: 1.21, server API version: 1.20)

FATAL: all hosts have already failed -- aborting

**Comment by frnsys** [comment]
Just ran into the same issue, confirming that setting docker-py to 1.2.3 fixes it.

**Comment by adubeniuk** [comment]
Just encountered the same issue with latest docker-py 1.8.1 and CentOS 7
Downgrading docker-py to 1.2.3 helped.

**Comment by mattclay** [comment]
These images have been [deprecated](https://github.com/ansible/ansible-docker-base/blob/master/README.md#these-images-have-been-deprecated) and are no longer supported.
