### ISSUE TITLE
screwed permissions in the image

### ISSUE THREAD

**Issue by ramelito** [ansible/ansible-docker-base#9]
i am using this base image to install freeradius server with simple playbook
---
- hosts: localhost

  tasks:
    - name: Run "apt-get update"
      apt: update_cache=yes

    - name: Update all packages to the latest version
      apt: upgrade=dist

    - name: install freeradius packages
      apt: name={{ item }} state=present
      with_items:
        - freeradius
        - freeradius-mysql
~                            
playbook successfully executed

root@defb89e31769:/opt/ansible# ansible-playbook site.yml -c local

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Run "apt-get update"] ************************************************** 
ok: [localhost]

TASK: [Update all packages to the latest version] ***************************** 
changed: [localhost]

TASK: [install freeradius packages] ******************************************* 
changed: [localhost] => (item=freeradius,freeradius-mysql)

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=2    unreachable=0    failed=0   

after this i am strting freeradius -X
which is stops with error
rlm_eap: SSL error error:0200100D:system library:fopen:Permission denied
rlm_eap_tls: Error reading private key file /etc/freeradius/certs/server.key
rlm_eap: Failed to initialize type tls
/etc/freeradius/eap.conf[17]: Instantiation failed for module "eap"
/etc/freeradius/sites-enabled/default[310]: Failed to load module "eap".
/etc/freeradius/sites-enabled/default[252]: Errors parsing authenticate section. 

meanwhile manual installtion in original ubuntu image works ok, no issue with permissions for root

here is complete dockerfile to reproduce issue
FROM ansible/ubuntu14.04-ansible:latest
ADD ansible /opt/ansible
WORKDIR /opt/ansible
RUN ansible-playbook site.yml -c local
EXPOSE 1812/udp 1813/udp
ENTRYPOINT ["/usr/sbin/freeradius", "-X"]

**Comment by gregdek** [comment]
@ramelito thanks for the PR.

Because of the variety of excellent Ansible Docker images on Dockerhub, we are deprecating our "official" Ansible Docker image. We will leave this repo active, but we will no longer accept pull requests or issues. Feel free to fork this repo and publish your own images to Dockerhub as you see fit. 

For a list of Ansible images on Dockerhub, you can look here: 

https://hub.docker.com/search/?q=ansible

Thanks!
